export const GET_METRIC_LIST_API_FAIL = 'EVENT/GET_METRIC_LIST_API_FAIL';
export const GET_METRIC_LIST_RESPONSE = 'EVENT/GET_METRIC_LIST_RESPONSE';

export const UPDATE_MEASUREMENTS_API_CALL_FAIL = 'EVENT/UPDATE_MEASUREMENTS_API_CALL_FAIL';
export const UPDATE_METRIC_MEASUREMENTS_RESPONSE = 'EVENT/UPDATE_METRIC_MEASUREMENTS_RESPONSE';

export const GET_MEASUREMENTS_API_CALL_FAIL = 'EVENT/GET_MEASUREMENTS_API_CALL_FAIL';
export const GET_METRICS_MEASUREMENTS_RESPONSE = 'EVENT/GET_METRICS_MEASUREMENTS_RESPONSE';
